Add NIP04 support
ethicnology/dart-nostr pull request #25
Opened 2023-04-11 05:04 UTC by no-prob

2023-04-11 08:13 UTC, ethicnology commented
@no-prob 

Please read: https://github.com/ethicnology/dart-nostr/pull/23#pullrequestreview-1347384099

2023-04-11 16:46 UTC, ntheden commented
> @no-prob
> 
> Please read: [#23 (review)](https://github.com/ethicnology/dart-nostr/pull/23#pullrequestreview-1347384099)

Yeah, I saw that after creating this PR. This PR has unit tests and integrates with Event class. But unit tests could be expanded and reducing dependencies down to just pointycastle is a good  suggestion. Also I could expand the documentation. I will make those changes a little later if someone else doesn't first, right now working on the project that depends on the nip 4 feature.

2023-04-12 08:36 UTC, ethicnology requested changes
Thanks for your work, i add some change you can do in order to keep the library modularity and make it easier to maintain over the time

2023-04-12 08:36 UTC, ethicnology commented on lib/src/ok.dart
Ok but corresponding unit test needed to keep a high level of code coverage

2023-04-12 08:36 UTC, ethicnology commented on lib/src/eose.dart
Ok but unit tests should be created to keep a high level of code coverage

2023-04-12 08:36 UTC, ethicnology commented on lib/src/event.dart
Could you remove all the changes you did to event.dart and create `src/nips/nip_004.dart` ?

In this file you will create a Nip4 which extends Events and add the attributes and methods you want implemented

see the design talk about nip12: https://github.com/ethicnology/dart-nostr/pull/24#issuecomment-1493204442

2023-04-12 08:36 UTC, ethicnology commented on lib/src/kepler.dart
May you put this into a folder `src/crypto/kepler.dart`

and add as a comment the link to the kepler file source

2023-04-12 08:36 UTC, ethicnology commented on lib/src/operator.dart
May you put this into a folder `src/crypto/operator.dart`

and add as a comment the link to the source file

2023-04-12 08:36 UTC, ethicnology commented on lib/src/settings.dart
I don't understand why you need these variables

2023-04-12 08:36 UTC, ethicnology commented on test/dm_test.dart
when you will have created `src/nips/nip_004.dart` you could put this test file in `test/nips/nip_004_test.dart`

2023-04-12 17:39 UTC, no-prob commented on lib/src/eose.dart
Agree, also I will move to a separate PR.

2023-04-12 17:39 UTC, no-prob commented on lib/src/event.dart
Ok

2023-04-12 17:44 UTC, no-prob commented on lib/src/settings.dart
`Kepler.byteSecret()` uses `scalarMultiple()` which pulls in all the rest.

2023-04-13 07:15 UTC, ethicnology commented
tell me when you think you are done

2023-04-13 15:31 UTC, no-prob commented
> tell me when you think you are done

I am done with this current PR.

2023-04-16 16:55 UTC, ethicnology commented on lib/src/event.dart
I will rework this part

2023-04-16 16:57 UTC, ethicnology approved these changes
Thank you for your contribution

I will rework some parts to keep it as close as possible as the way the library is already implemented

2023-04-16 16:57 UTC, merged