Add a tag to filter
ethicnology/dart-nostr pull request #33
Opened 2023-08-29 21:13 UTC by bigOconstant

There is a new tag, called a tag.

2023-08-30 07:23 UTC, ethicnology commented
Hello, thanks for this quick update as they changed the [NIP01 some hours ago](https://github.com/nostr-protocol/nips/commit/e50bf508d9014cfb19bfa8a5c4ec88dc4788d490).

I try to maintain a high percentage of code coverage in this library so if you want this to be merged you should complete the job with a unit test of this new attribute

2023-08-30 07:24 UTC, ethicnology requested changes
Unit test is missing

2023-08-30 07:26 UTC, ethicnology commented
As you noticed in #34 you may implement this new tag in filter and the matching unit test

2023-08-30 11:08 UTC, bigOconstant commented
> As you noticed in #34 you may implement this new tag in filter and the matching unit test

I added the a tag to the filter_test.dart and requests_test.dart unit test which seemed to fit. Let me know if that is enough.

2023-09-01 21:55 UTC, ethicnology approved these changes
Some rework that i will perform

2023-09-01 21:55 UTC, ethicnology commented on test/filter_test.dart
> +      expect(filter.e, e);
filter.a, a

2023-09-01 21:55 UTC, ethicnology commented on test/filter_test.dart
> +      expect(filter.e, e);
i will fix it myself

2023-09-01 21:56 UTC, merged

2023-09-02 12:21 UTC, bigOconstant commented on test/filter_test.dart
> +      expect(filter.e, e);
Oops thank you